### ISSUE TITLE
Creating your own quote

### ISSUE THREAD

**Issue by amlew00** [quotestream/quotestream.github.io#4] opened 2018-10-17 23:08 UTC
Text box for author gets covered by the keyboard on iPhone 6s.

**Comment by amlew00** [comment] 2018-10-17 23:09
Nothing happens when hitting submit after creating a quote

**Comment by quotestream** [comment] 2018-10-18 19:17
Input / keyboard bug is fixed 0.5.0

However, I was not able to reproduce the quote contribution bug. Can you try again with the latest build and provide a screenshot of where it is stuck?

![screen shot 2018-10-18 at 3 15 45 pm](https://user-images.githubusercontent.com/41097502/47178290-c7bb8100-d2e8-11e8-85c5-c92ec8512557.png)

![screen shot 2018-10-18 at 3 16 09 pm](https://user-images.githubusercontent.com/41097502/47178304-d86bf700-d2e8-11e8-916c-aa1d65e3c9c6.png)

**Comment by amlew00** [comment] 2018-10-18 19:39
![0d1500bb-5454-4a6a-ab3a-859bad3b6fdc](https://user-images.githubusercontent.com/44245093/47179391-f7b85380-d2eb-11e8-9a0f-57c2f15da552.png)

**Comment by amlew00** [comment] 2018-10-18 19:40
It stays stuck on this screen after hitting submit

**Comment by quotestream** [comment] 2018-10-19 10:52
I was able to reproduce this.. debugging

**Comment by quotestream** [comment] 2018-10-19 10:56
Fixed in 0.6.0

<img width="411" alt="screen shot 2018-10-19 at 6 55 39 am" src="https://user-images.githubusercontent.com/41097502/47214483-12caa800-d36c-11e8-8e33-8a28ad1468a3.png">

**Closed** 2018-10-19 10:56 UTC
Labels: bug, question
